-- create database gestion_produccion;
use gestion_produccion;

CREATE TABLE CUSTOMERS(
	ID_CUSTOMER INTEGER AUTO_INCREMENT PRIMARY KEY,
    RUC INTEGER (11) NOT NULL UNIQUE,
	RAZON_SOCIAL VARCHAR (30) NOT NULL UNIQUE
);

CREATE TABLE COLORS(
	ID_COLOR INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(30) NOT NULL
);

CREATE TABLE MATERIALS(
	ID_MATERIAL INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(30) NOT NULL
);

CREATE TABLE FACTURAS(
	ID_FACTURA INTEGER AUTO_INCREMENT PRIMARY KEY,
    CODIGO VARCHAR(20) NOT NULL
);

CREATE TABLE STATES(
	ID_STATE INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE SPACES(
	ID_SPACE INTEGER AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE PRODUCTS(
	ID_PRODUCT INTEGER AUTO_INCREMENT PRIMARY KEY,
    TIPO_PRODUCTO VARCHAR(50) NOT NULL,
	DIAMETER VARCHAR(10) NOT NULL,
    DESCRIPCION VARCHAR (50) NOT NULL
);

CREATE TABLE PRIMARY_MATERIALS(
	ID_PRIMATER INTEGER AUTO_INCREMENT PRIMARY KEY,-- SE CONECTARA CON MATERIAL Y COLOR
    ID_MATERIAL INTEGER NOT NULL,
    ID_COLOR INTEGER,
    DESCRIPCION VARCHAR(30),
    DENIER INTEGER(5),
    FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIALS(ID_MATERIAL),
    FOREIGN KEY (ID_COLOR) REFERENCES COLORS(ID_COLOR)
);

CREATE TABLE ORDERS(
	ID_ORDER INTEGER AUTO_INCREMENT PRIMARY KEY,
    ID_CUSTOMER INTEGER NOT NULL,
    ID_STATE INTEGER NOT NULL,
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,-- SE COLOCARA AUTOMATICAMENTE CN FECHA Y HORA CUANDO SE CREE UN PEDIDO
    FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMERS(ID_CUSTOMER),
    FOREIGN KEY (ID_STATE) REFERENCES STATES(ID_STATE)
);

CREATE TABLE STOCK_ZONE(
	ID_STOCK_ZONE INTEGER AUTO_INCREMENT PRIMARY KEY,
    ID_SPACE INTEGER NOT NULL,
    ID_PRIMATER INTEGER NOT NULL,
    PESO DECIMAL(10,2) NOT NULL,
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OBSERVACION VARCHAR(100),
    FOREIGN KEY (ID_SPACE) REFERENCES SPACES(ID_SPACE),
    FOREIGN KEY (ID_PRIMATER) REFERENCES PRIMARY_MATERIALS(ID_PRIMATER)
);

CREATE TABLE STOCK_MOVEMENTS_PRIMARY(
	ID_MOVEMENT INTEGER AUTO_INCREMENT PRIMARY KEY,
    ID_ORIGIN_ZONE INTEGER NOT NULL,
    ID_DESTINATION_ZONE INTEGER NOT NULL,
    ID_PRIMATER INTEGER NOT NULL,
    CANTIDAD DECIMAL(10,2) NOT NULL,
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    OBSERVACION VARCHAR(100),
    FOREIGN KEY(ID_ORIGIN_ZONE) REFERENCES SPACES(ID_SPACE),
    FOREIGN KEY(ID_DESTINATION_ZONE) REFERENCES SPACES(ID_SPACE),
    FOREIGN KEY(ID_PRIMATER) REFERENCES PRIMARY_MATERIALS(ID_PRIMATER)
);

CREATE TABLE STOCK_FINISHED_PRODUCT(
	ID_PRO INTEGER AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUCT INTEGER NOT NULL,
    ID_SPACE INTEGER NOT NULL,
    PESO DECIMAL(10,2) NOT NULL,
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCTS(ID_PRODUCT),
	FOREIGN KEY(ID_SPACE) REFERENCES SPACES(ID_SPACE)
);

CREATE TABLE PRODUCT_COMPOSITION(
	ID_COMPOSITION INTEGER AUTO_INCREMENT PRIMARY KEY,
    ID_PRODUCT INTEGER NOT NULL,
    ID_PRIMATER INTEGER NOT NULL,
    ZONE VARCHAR(20) NOT NULL,
    PERCENTAGE FLOAT NOT NULL,
    FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCTS(ID_PRODUCT),
    FOREIGN KEY(ID_PRIMATER) REFERENCES PRIMARY_MATERIALS(ID_PRIMATER)
);

CREATE TABLE DESCRIPTION_ORDER(
		ID_DESCRIPTION_ORDER INTEGER AUTO_INCREMENT PRIMARY KEY,
        ID_PRODUCT INTEGER NOT NULL,
        ID_ORDER INTEGER NOT NULL,
        PESO DECIMAL (10,2) NOT NULL,
        PRESENTACION DECIMAL(10,2) NOT NULL,
		FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCTS(ID_PRODUCT),
        FOREIGN KEY(ID_ORDER) REFERENCES ORDERS(ID_ORDER)
);W

CREATE TABLE ORDER_DELIVERY(
	ID_ORDER_DELIVERY INTEGER AUTO_INCREMENT PRIMARY KEY,
    ID_ORDER INTEGER NOT NULL,
    ID_FACTURA INTEGER,
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(ID_ORDER) REFERENCES ORDERS(ID_ORDER),
    FOREIGN KEY(ID_FACTURA) REFERENCES FACTURAS(ID_FACTURA)
);

CREATE TABLE DESCRIPTION_DELIVERY(
	ID_DESCRIPTION_DELIVERY INTEGER AUTO_INCREMENT PRIMARY KEY,
    ID_ORDER_DELIVERY INTEGER NOT NULL,
    PESO DECIMAL(10,2) NOT NULL,
    DESCRIPCION VARCHAR(50),
    FOREIGN KEY(ID_ORDER_DELIVERY) REFERENCES ORDER_DELIVERY(ID_ORDER_DELIVERY)
);




















